version: '3.8'

services:
  # Redis - Otimizado para 4GB RAM
  redis:
    image: redis:7-alpine  # Versão leve (Alpine Linux)
    container_name: growchats_redis
    ports:
      - "6379:6379"
    # Limita uso de memória do Redis
    command: redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  redis_data:
    driver: local